services:
  web:
    image: ghcr.io/happyhackingspace/web-dvwa
    ports:
      - "80:80"
    environment:
      - MYSQL_ROOT_PASSWORD=p@ssw0rd
    volumes:
      - data:/var/lib/mysql
    networks:
      - network

volumes:
  data:

networks:
  network:
    driver: bridge
