services:
  database:
    image: ghcr.io/happyhackingspace/mutillidae-database:latest
    networks:
      - datanet

  database_admin:
    depends_on:
      - database
    image: ghcr.io/happyhackingspace/mutillidae-database_admin:latest
    ports:
      - 127.0.0.1:81:80
    networks:
      - datanet

  www:
    depends_on:
      - database
      - directory
    image: ghcr.io/happyhackingspace/mutillidae-www:latest
    ports:
      - 127.0.0.1:80:80
      - 127.0.0.1:443:443
    networks:
      - datanet
      - ldapnet

  directory:
    image: ghcr.io/happyhackingspace/mutillidae-ldap:latest
    volumes:
      - ldap_data:/var/lib/ldap
      - ldap_config:/etc/ldap/slapd.d
    ports:
      - 127.0.0.1:389:389
    networks:
      - ldapnet

  directory_admin:
    depends_on:
      - directory
    image: ghcr.io/happyhackingspace/mutillidae-ldap_admin:latest
    ports:
      - 127.0.0.1:82:80
    networks:
      - ldapnet

volumes:
  ldap_data:
  ldap_config:

networks:
  datanet:
  ldapnet:
