version: '3'

services:
  sickchill:
    image: ghcr.io/happyhackingspace/sickchill:2024.3.1
    container_name: sickchill
    restart: unless-stopped
    ports:
      - "8081:8081"
    environment:
      - TZ=Europe/Istanbul
